server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a982338665/config-spring-cloud20201130.git #GitHub上面的git仓库名字
#          uri: git@github.com:a982338665/config-spring-cloud20201130.git #GitHub上面的git仓库名字
#          uri: git@github.com:zzyybs/springcloud-config.git #GitHub上面的git仓库名字
        ####搜索目录
          search-paths:
            - config-spring-cloud20201130
#            - springcloud-config
      ####读取分支
      label: main #已被变更为main分支
#      label: master

#rabbitmq相关配置
  rabbitmq:
      host: 122.51.144.140
      port: 5672
      username: user
      password: pwd

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置,暴露bus刷新配置的端点
#监控刷新一定要有pom依赖：spring-boot-starter-actuator
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

